---
# Publishing the package to the npm registry when the version number changes
# See https://github.com/marketplace/actions/npm-publish for more information
name: Publish Package to npmjs

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true
      - run: pnpm install --frozen-lockfile
      - run: moon :build
      - run: pnpm publish --no-git-checks -r
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


